/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PuzzlesColorSortRouteRouteImport } from './routes/puzzles/color-sort/route'
import { Route as PuzzlesNonogramRouteRouteImport } from './routes/puzzles/nonogram/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesColorSortRouteRoute = PuzzlesColorSortRouteRouteImport.update({
  id: '/puzzles/color-sort',
  path: '/puzzles/color-sort',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesNonogramRouteRoute = PuzzlesNonogramRouteRouteImport.update({
  id: '/puzzles/nonogram',
  path: '/puzzles/nonogram',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/puzzles/color-sort': typeof PuzzlesColorSortRouteRoute
  '/puzzles/nonogram': typeof PuzzlesNonogramRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/puzzles/color-sort': typeof PuzzlesColorSortRouteRoute
  '/puzzles/nonogram': typeof PuzzlesNonogramRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/puzzles/color-sort': typeof PuzzlesColorSortRouteRoute
  '/puzzles/nonogram': typeof PuzzlesNonogramRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/puzzles/color-sort' | '/puzzles/nonogram'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/puzzles/color-sort' | '/puzzles/nonogram'
  id: '__root__' | '/' | '/puzzles/color-sort' | '/puzzles/nonogram'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PuzzlesColorSortRouteRoute: typeof PuzzlesColorSortRouteRoute
  PuzzlesNonogramRouteRoute: typeof PuzzlesNonogramRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/color-sort': {
      id: '/puzzles/color-sort'
      path: '/puzzles/color-sort'
      fullPath: '/puzzles/color-sort'
      preLoaderRoute: typeof PuzzlesColorSortRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/nonogram': {
      id: '/puzzles/nonogram'
      path: '/puzzles/nonogram'
      fullPath: '/puzzles/nonogram'
      preLoaderRoute: typeof PuzzlesNonogramRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PuzzlesColorSortRouteRoute: PuzzlesColorSortRouteRoute,
  PuzzlesNonogramRouteRoute: PuzzlesNonogramRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
